const Hiname = require('./2-method')
const name = require('./1-name')
const name3 = require('./3-alternayive-syntex')
require('./4-mind-Grenade')
    // Hiname(name.ismail)
    // Hiname(name.ismail2)
    // console.log(name3)